### ISSUE TITLE
Capítulo 6 - Interpretación semiótica de la dialógica

### ISSUE THREAD

**Issue by ivanvgav** [ivanvgav/thesis-uidge#1]
- [x] Escritura de borrador
- [x] #3
- [x] Exportación individual para revisión
- [ ] Corrección de revisiones
- [ ] Retoques para la conexión con toda la tesis

### *Ad-hoc* issues

- [x] #6

**Comment by ivanvgav** [comment]
Falta revisar los TODOs que son acciones para completar el capítulo.

**Comment by ivanvgav** [comment]
Se hizo la tabla de latex pero lo que no pude hacer es el estilo de la tabla para que se vean bien.

Tengo que mejorar eso:

### TODO
- [ ] Que aparezcan las líneas de las columnas de las tablas dialógicas

**Comment by ivanvgav** [comment]
Creo que lo mejor que se puede hacer es tener cada capítulo en un Google Docs para que la gente pueda comentar y hacer sugerencias de la mejor manera posible. 

Así dejo de joder con los conversores y las cosas.

- [ ] Transformar el capítulo en un documento de Google Docs

**Comment by ivanvgav** [comment]
> Creo que lo mejor que se puede hacer es tener cada capítulo en un Google Docs para que la gente pueda comentar y hacer sugerencias de la mejor manera posible.
> 
> Así dejo de joder con los conversores y las cosas.
> 
> * [ ]  Transformar el capítulo en un documento de Google Docs

Esto es algo que no tengo que hacer. No tiene mucho sentido

**Comment by ivanvgav** [comment]
Tengo que reescribir todo esto. Algo bueno capaz que pueda sacar, pero bien no sé que es lo que puedo sacar. Por el momento tengo que cerrar esto y volver con el otro repositorio.
